# NumPy Exercises 


## Defining an array


#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [5]:
array=np.ones(10)
print("An array of 10 ones:")
print(array)

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 tens

In [6]:
array=np.ones(10)*10
print("An array of 10 tens:")
print(array)

An array of 10 tens:
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


#### Create an array of the integers from 10 to 100

In [8]:
array=np.arange(10,101)
print("Array of the integers from 10 to 100")
print(array)

Array of the integers from 10 to 100
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### Create an array of all the odd integers from 10 to 30

In [47]:
start, end = 10, 30
  
# iterating each number in list
for num in range(start, end + 1):
      
    # checking condition
    if num % 2 != 0:
        print(num, end = " ")

11 13 15 17 19 21 23 25 27 29 

#### Create a 3x3 array with values ranging from 0 to 8 

In [14]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create an array of 25 random numbers between 0 and 1

In [19]:
import numpy as np
rand_num = np.random.normal(0,1,25)
print("25 Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-1.42392528 -0.39291934 -0.2760079  -0.65621542  0.65193368 -0.01495676
 -0.13525333 -0.10709655 -0.16975519  0.34217225 -0.53740254 -0.15934899
  0.99119042  1.00852534 -0.89961376  0.06455755 -1.015474   -0.2283973
  1.57101048 -1.01872266  0.23600404  0.17423594 -0.73665699  1.24576648
  0.15637669]


#### Create an array of 40 linearly spaced points between 0 and 10:

In [21]:
import numpy as np
arr=np.linspace(0, 1, 40)
print(arr)

[0.         0.02564103 0.05128205 0.07692308 0.1025641  0.12820513
 0.15384615 0.17948718 0.20512821 0.23076923 0.25641026 0.28205128
 0.30769231 0.33333333 0.35897436 0.38461538 0.41025641 0.43589744
 0.46153846 0.48717949 0.51282051 0.53846154 0.56410256 0.58974359
 0.61538462 0.64102564 0.66666667 0.69230769 0.71794872 0.74358974
 0.76923077 0.79487179 0.82051282 0.84615385 0.87179487 0.8974359
 0.92307692 0.94871795 0.97435897 1.        ]


## Indexing 


In [31]:
#You are given the following 2D array
a = np.arange(1,25).reshape(4,-1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [33]:
a[1:4,2:]

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

In [32]:
# Use array indexing  get the value 20, as my output shows
a[3,1]

20

In [34]:
# Use array indexing  get the column 10, 16, 22, as my output shows
a[1:4,3:4]

array([[10],
       [16],
       [22]])

In [35]:
# Use array indexing  get the row [15,16,17] as my output shows
a[2:3,2:5]

array([[15, 16, 17]])

### Now the hard task!

#### Write a function that gives the users four random integers between 1 and 10 and ask them to enter the square number of them. If the user answers all of them correctly, congratulate them. Otherwise, show them the right answer

In [37]:
import numpy as np
import random #import required packages

def getRandomSquares():
    rand_numbers=np.asarray(random.sample(range(1,11),4))

    squares=[number*number for number in rand_numbers]
    print("Enter squares of each number in list " ,rand_numbers) #printing rand_numbers
    input_array=np.array([],dtype=int) #creating an empty numpy array

    for i in range (0,4): #iterate the loop
        print("Enter square of " + str(rand_numbers[i]) + ": ",end="") #asking user to enter the square of number

        num=int(input("")) #taking number from user

        input_array=np.append(input_array,num)
    result=input_array==squares #comparing user input squares and computed squares

    if all(result)==True:
      print("Congratulations...")
    else:
      print("Incorrected answers: ") #printing incorrected answers

    for i in range(0,len(result)):
        if result[i]==False:
            print("You have entered square of {} is {}. The correct square value is {}".format(rand_numbers[i],input_array[i],squares[i]))

getRandomSquares()





    

Enter squares of each number in list  [2 6 9 3]
Enter square of 2: 4
Enter square of 6: 36
Enter square of 9: 81
Enter square of 3: 9
Congratulations...
